[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Uncomment to use this redirect for Single Page Applications
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Define headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.googletagmanager.com *.google-analytics.com *.callrail.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: *.cloudinary.com blob: *.google-analytics.com; font-src 'self'; connect-src 'self' *.google-analytics.com *.callrail.com; frame-src 'self'"
